apiVersion: batch.example.com/v1
kind: TaskRunner
metadata:
  labels:
    app.kubernetes.io/name: taskrunner-operator
    app.kubernetes.io/managed-by: kustomize
  name: taskrunner-sample
spec:
  # TODO(user): Add fields here
