apiVersion: sample.sample.io/v1
kind: Sample
metadata:
  labels:
    app.kubernetes.io/name: sample-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample-sample
spec:
  # TODO(user): Add fields here
